# TCL File Generated by Component Editor 21.1
# Sun Sep 21 23:03:53 MSK 2025
# DO NOT MODIFY


# 
# ahb_to_ext_bridge "ahb_to_ext_bridge" v1.0
#  2025.09.21.23:03:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ahb_to_ext_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME ahb_to_ext_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ahb_to_ext_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ahb_to_ext_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ahb_to_ext_bridge.sv SYSTEM_VERILOG PATH src/ahb_to_ext_bridge.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AHB_ADDR_W INTEGER 32 ""
set_parameter_property AHB_ADDR_W DEFAULT_VALUE 32
set_parameter_property AHB_ADDR_W DISPLAY_NAME AHB_ADDR_W
set_parameter_property AHB_ADDR_W WIDTH ""
set_parameter_property AHB_ADDR_W TYPE INTEGER
set_parameter_property AHB_ADDR_W UNITS None
set_parameter_property AHB_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AHB_ADDR_W DESCRIPTION ""
set_parameter_property AHB_ADDR_W HDL_PARAMETER true
add_parameter AHB_DATA_W INTEGER 32 ""
set_parameter_property AHB_DATA_W DEFAULT_VALUE 32
set_parameter_property AHB_DATA_W DISPLAY_NAME AHB_DATA_W
set_parameter_property AHB_DATA_W WIDTH ""
set_parameter_property AHB_DATA_W TYPE INTEGER
set_parameter_property AHB_DATA_W UNITS None
set_parameter_property AHB_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AHB_DATA_W DESCRIPTION ""
set_parameter_property AHB_DATA_W HDL_PARAMETER true
add_parameter EXT_ADDR_W INTEGER 30 ""
set_parameter_property EXT_ADDR_W DEFAULT_VALUE 30
set_parameter_property EXT_ADDR_W DISPLAY_NAME EXT_ADDR_W
set_parameter_property EXT_ADDR_W WIDTH ""
set_parameter_property EXT_ADDR_W TYPE INTEGER
set_parameter_property EXT_ADDR_W UNITS None
set_parameter_property EXT_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EXT_ADDR_W DESCRIPTION ""
set_parameter_property EXT_ADDR_W HDL_PARAMETER true
add_parameter EXT_DATA_W INTEGER 32
set_parameter_property EXT_DATA_W DEFAULT_VALUE 32
set_parameter_property EXT_DATA_W DISPLAY_NAME EXT_DATA_W
set_parameter_property EXT_DATA_W TYPE INTEGER
set_parameter_property EXT_DATA_W UNITS None
set_parameter_property EXT_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EXT_DATA_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point AHB_s
# 
add_interface AHB_s conduit end
set_interface_property AHB_s associatedClock clock
set_interface_property AHB_s associatedReset ""
set_interface_property AHB_s ENABLED true
set_interface_property AHB_s EXPORT_OF ""
set_interface_property AHB_s PORT_NAME_MAP ""
set_interface_property AHB_s CMSIS_SVD_VARIABLES ""
set_interface_property AHB_s SVD_ADDRESS_GROUP ""

add_interface_port AHB_s hsel hsel Input 1
add_interface_port AHB_s haddr haddr Input "((AHB_ADDR_W-1)) - (0) + 1"
add_interface_port AHB_s htrans htrans Input 2
add_interface_port AHB_s hwrite hwrite Input 1
add_interface_port AHB_s hsize hsize Input 3
add_interface_port AHB_s hwdata hwdata Input "((AHB_DATA_W-1)) - (0) + 1"
add_interface_port AHB_s hreadyout hreadyout Output 1
add_interface_port AHB_s hrdata hrdata Output "((AHB_DATA_W-1)) - (0) + 1"
add_interface_port AHB_s hresp hresp Output 2


# 
# connection point ExtBus_m
# 
add_interface ExtBus_m conduit end
set_interface_property ExtBus_m associatedClock ""
set_interface_property ExtBus_m associatedReset ""
set_interface_property ExtBus_m ENABLED true
set_interface_property ExtBus_m EXPORT_OF ""
set_interface_property ExtBus_m PORT_NAME_MAP ""
set_interface_property ExtBus_m CMSIS_SVD_VARIABLES ""
set_interface_property ExtBus_m SVD_ADDRESS_GROUP ""

add_interface_port ExtBus_m ext_addr export_address Output "((EXT_ADDR_W-1)) - (0) + 1"
add_interface_port ExtBus_m ext_byteenable export_byte_enable Output "(((EXT_DATA_W/8)-1)) - (0) + 1"
add_interface_port ExtBus_m ext_rdata export_read_data Input "((EXT_DATA_W-1)) - (0) + 1"
add_interface_port ExtBus_m ext_read export_read Output 1
add_interface_port ExtBus_m ext_wdata export_write_data Output "((EXT_DATA_W-1)) - (0) + 1"
add_interface_port ExtBus_m ext_write export_write Output 1
add_interface_port ExtBus_m ext_ack export_acknowledge Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset Input 1

