# TCL File Generated by Component Editor 21.1
# Mon Sep 22 20:03:09 MSK 2025
# DO NOT MODIFY


# 
# wally_wrapper "wally_wrapper" v1.0
#  2025.09.22.20:03:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module wally_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME wally_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME wally_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL wally_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file wally_wrapper.sv SYSTEM_VERILOG PATH ../../src/wallypipelinedsocwrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AHBW INTEGER 32
set_parameter_property AHBW DEFAULT_VALUE 32
set_parameter_property AHBW DISPLAY_NAME AHBW
set_parameter_property AHBW TYPE INTEGER
set_parameter_property AHBW UNITS None
set_parameter_property AHBW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AHBW HDL_PARAMETER true
add_parameter PA_BITS INTEGER 32
set_parameter_property PA_BITS DEFAULT_VALUE 32
set_parameter_property PA_BITS DISPLAY_NAME PA_BITS
set_parameter_property PA_BITS TYPE INTEGER
set_parameter_property PA_BITS UNITS None
set_parameter_property PA_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PA_BITS HDL_PARAMETER true
add_parameter XLEN INTEGER 32
set_parameter_property XLEN DEFAULT_VALUE 32
set_parameter_property XLEN DISPLAY_NAME XLEN
set_parameter_property XLEN TYPE INTEGER
set_parameter_property XLEN UNITS None
set_parameter_property XLEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XLEN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_out
# 
add_interface reset_out reset start
set_interface_property reset_out associatedClock clock
set_interface_property reset_out associatedDirectReset ""
set_interface_property reset_out associatedResetSinks ""
set_interface_property reset_out synchronousEdges DEASSERT
set_interface_property reset_out ENABLED true
set_interface_property reset_out EXPORT_OF ""
set_interface_property reset_out PORT_NAME_MAP ""
set_interface_property reset_out CMSIS_SVD_VARIABLES ""
set_interface_property reset_out SVD_ADDRESS_GROUP ""

add_interface_port reset_out reset reset Output 1


# 
# connection point reset_inp
# 
add_interface reset_inp reset end
set_interface_property reset_inp associatedClock clock
set_interface_property reset_inp synchronousEdges DEASSERT
set_interface_property reset_inp ENABLED true
set_interface_property reset_inp EXPORT_OF ""
set_interface_property reset_inp PORT_NAME_MAP ""
set_interface_property reset_inp CMSIS_SVD_VARIABLES ""
set_interface_property reset_inp SVD_ADDRESS_GROUP ""

add_interface_port reset_inp reset_ext reset Input 1


# 
# connection point conduit_trash
# 
add_interface conduit_trash conduit end
set_interface_property conduit_trash associatedClock clock
set_interface_property conduit_trash associatedReset ""
set_interface_property conduit_trash ENABLED true
set_interface_property conduit_trash EXPORT_OF ""
set_interface_property conduit_trash PORT_NAME_MAP ""
set_interface_property conduit_trash CMSIS_SVD_VARIABLES ""
set_interface_property conduit_trash SVD_ADDRESS_GROUP ""

add_interface_port conduit_trash HRESETn trash4 Output 1
add_interface_port conduit_trash HCLK trash2 Output 1
add_interface_port conduit_trash HWSTRB trash5 Output "(((XLEN/8)-1)) - (0) + 1"
add_interface_port conduit_trash HMASTLOCK trash3 Output 1
add_interface_port conduit_trash TIMECLK trash6 Input 1
add_interface_port conduit_trash ExternalStall trash1 Input 1
add_interface_port conduit_trash HBURST hburst Output 3
add_interface_port conduit_trash HPROT hprot Output 4
add_interface_port conduit_trash HREADY hreadyin Output 1


# 
# connection point GPIO
# 
add_interface GPIO conduit end
set_interface_property GPIO associatedClock clock
set_interface_property GPIO associatedReset ""
set_interface_property GPIO ENABLED true
set_interface_property GPIO EXPORT_OF ""
set_interface_property GPIO PORT_NAME_MAP ""
set_interface_property GPIO CMSIS_SVD_VARIABLES ""
set_interface_property GPIO SVD_ADDRESS_GROUP ""

add_interface_port GPIO GPIOEN export1 Output 32
add_interface_port GPIO GPIOIN export2 Input 32
add_interface_port GPIO GPIOOUT export3 Output 32


# 
# connection point UART
# 
add_interface UART conduit end
set_interface_property UART associatedClock clock
set_interface_property UART associatedReset ""
set_interface_property UART ENABLED true
set_interface_property UART EXPORT_OF ""
set_interface_property UART PORT_NAME_MAP ""
set_interface_property UART CMSIS_SVD_VARIABLES ""
set_interface_property UART SVD_ADDRESS_GROUP ""

add_interface_port UART UARTSin export1 Input 1
add_interface_port UART UARTSout export2 Output 1


# 
# connection point SDC
# 
add_interface SDC conduit end
set_interface_property SDC associatedClock clock
set_interface_property SDC associatedReset ""
set_interface_property SDC ENABLED true
set_interface_property SDC EXPORT_OF ""
set_interface_property SDC PORT_NAME_MAP ""
set_interface_property SDC CMSIS_SVD_VARIABLES ""
set_interface_property SDC SVD_ADDRESS_GROUP ""

add_interface_port SDC SDCCLK export1 Output 1
add_interface_port SDC SDCCS export2 Output 4
add_interface_port SDC SDCCmd export3 Output 1
add_interface_port SDC SDCIn export4 Input 1


# 
# connection point SPI
# 
add_interface SPI conduit end
set_interface_property SPI associatedClock clock
set_interface_property SPI associatedReset ""
set_interface_property SPI ENABLED true
set_interface_property SPI EXPORT_OF ""
set_interface_property SPI PORT_NAME_MAP ""
set_interface_property SPI CMSIS_SVD_VARIABLES ""
set_interface_property SPI SVD_ADDRESS_GROUP ""

add_interface_port SPI SPICLK export1 Output 1
add_interface_port SPI SPICS export2 Output 4
add_interface_port SPI SPIIn export3 Input 1
add_interface_port SPI SPIOut export4 Output 1


# 
# connection point AHB_m
# 
add_interface AHB_m conduit end
set_interface_property AHB_m associatedClock clock
set_interface_property AHB_m associatedReset reset_out
set_interface_property AHB_m ENABLED true
set_interface_property AHB_m EXPORT_OF ""
set_interface_property AHB_m PORT_NAME_MAP ""
set_interface_property AHB_m CMSIS_SVD_VARIABLES ""
set_interface_property AHB_m SVD_ADDRESS_GROUP ""

add_interface_port AHB_m HWRITE hwrite Output 1
add_interface_port AHB_m HSIZE hsize Output 3
add_interface_port AHB_m HTRANS htrans Output 2
add_interface_port AHB_m HADDR haddr Output "((PA_BITS-1)) - (0) + 1"
add_interface_port AHB_m HWDATA hwdata Output "((AHBW-1)) - (0) + 1"
add_interface_port AHB_m HRDATAEXT hrdata Input "((AHBW-1)) - (0) + 1"
add_interface_port AHB_m HRESPEXT hresp Input 2
add_interface_port AHB_m HSELEXT hsel Output 1
add_interface_port AHB_m HREADYEXT hreadyout Input 1

